export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const PASSWORD_CHANGED = 'PASSWORD_CHANGED';
export const CONFIRM_PASSWORD_CHANGED = 'CONFIRM_PASSWORD_CHANGED';
export const CREATE_USER_FULFILLED = 'CREATE_USER_FULFILLED';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';

export const FIRST_NAME_CHANGED = 'FIRST_NAME_CHANGED';
export const AGE_CHANGED = 'AGE_CHANGED';
export const CITY_CHANGED = 'CITY_CHANGED';
export const ZIP_CODE_CHANGED = 'ZIP_CODE_CHANGED';
export const DESCRIPTION_CHANGED = 'DESCRIPTION_CHANGED';
export const INFLUENCES_CHANGED = 'INFLUENCES_CHANGED';
export const UPDATE_USER_FULFILLED = 'UPDATE_USER_FULFILLED';
export const GET_USER_FULFILLED = 'GET_USER_FULFILLED';

export const FETCH_INSTRUMENTS_FULFILLED = 'FETCH_INSTRUMENTS_FULFILLED';
export const UPDATE_USER_INSTRUMENTS_FULFILLED = 'UPDATE_USER_INSTRUMENTS_FULFILLED';
export const GET_USER_INSTRUMENTS_FULFILLED = 'GET_USER_INSTRUMENTS_FULFILLED';

export const GET_USERS_FULFILLED = 'GET_USERS_FULFILLED';
export const GET_FOREIGN_USER_FULFILLED = 'GET_FOREIGN_USER_FULFILLED';
export const GET_MATCHED_USERS_FULFILLED = 'GET_MATCHED_USERS_FULFILLED';
export const MATCH_USERS_FULFILLED = 'MATCH_USERS_FULFILLED';
